### PR TITLE
Revamping Ferveo Ciphertexts (breaking changes ⚠️ )

### LINKED ISSUE #144: Remove unused `construct_tag_hash` and `Ciphertext.check()`
There's currently 2 versions of `construct_tag_hash()`, and on of them seems incorrect:
https://github.com/nucypher/ferveo/blob/434fd5d07b54e72d120e9aa06cbc3e47848e6bcf/tpke/src/ciphertext.rs#L45-L51

As you can see, the AAD is not there. It's also just used here:
https://github.com/nucypher/ferveo/blob/434fd5d07b54e72d120e9aa06cbc3e47848e6bcf/tpke/src/ciphertext.rs#L36

This is part the function `Ciphertext.check()`, which is unused. 

I propose removing both.

### LINKED ISSUE #146: Use AAD as input of Chacha20Poly1305.encrypt()
We're currently relying on validating the AAD as part of the TPKE public verifiability function, but not as part of Chacha20Poly1305's properties as an AEAD cipher. That is, as a defense in depth measure, we could include the AAD as input when encrypting & decrypting with Chacha20Poly1305. 

See https://docs.rs/aead/0.5.1/aead/struct.Payload.html

### LINKED ISSUE #147: Instead of the symmetric ciphertext, pass its hash when creating/checking the auth_tag
One of the steps of the creating and checking the `Ciphertext` authentication tag is to compute a G2 hash element as follows (in pseudocode):
```pseudo
   tag = hash_to_G2(commitment_U, sym_ciphertext, aad)
```
However, this forces that anyone performing ciphertext validation (e.g. Ursula) must pass the symmetric ciphertext, which can be very inefficient. Instead, let's just pass a hash of the ciphertext:
```pseudo
   tag = hash_to_G2(commitment_U, sym_ciphertext_hash, aad)
```
With this change, the consumer would never have to include the bulk of the symmetric ciphertext in the decryption request, but only it's hash, which even has a known size.

### PR DESCRIPTION
**Pull request by cygnusv**
**Type of PR:**
- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [x] Refactor
- [ ] Other

**Required reviews:** 
- [ ] 1
- [ ] 2
- [X] 3

**What this does:**
Some of the changes introduced by this PR, all of them related with how ciphertexts are produced and used:
* Actually use the AAD input of the AEAD API of Chacha20Poly1305
    * Closes #146 
* Decouple the bulk of symmetric ciphertext from validation; instead just use the hash. This allows to have a small (and also constant!) decryption request. 
    * Closes #147 
    * Implies changes in nucypher-core and nucypher (TBD)
* Refactor `Ciphertext` implementation.
    * Fixes #144 
    * Remove unused & incorrect ciphertext length method (see #145 )

Apart from this, bumps MSRV to 1.67.0, and associated clippy changes.

**Why it's needed:**
@jMyles and @KPrasch identified an important limitation of current ciphertexts and TDec requests construction. Essentially, the TDec request included the full ciphertext, which implies a big overhead even for relatively small media files (e.g. short audio clips). The main goal of this PR was to decouple the bulk of symmetric ciphertext from the validation procedure, using a  hash instead. This enables very small TDec requests ( see #147). In the nucypher side, will allow to close https://github.com/nucypher/nucypher/issues/3176 via https://github.com/nucypher/nucypher/pull/3194

**Notes for reviewers:**
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?

### CODE REVIEW

**Comment by piotr-roslaniec** [comment]
The [error on CI](https://github.com/nucypher/ferveo/actions/runs/5712829254/job/15477070393?pr=149#step:4:160) is unrelated to this PR. In order to fix it, replace [this line](https://github.com/nucypher/ferveo/blob/main/.github/workflows/workspace.yml#L109-L109) with:
```
cargo install --version 0.11.1 wasm-pack
```

**Review by piotr-roslaniec — APPROVED** [review]
LGTM :tada: 

(I realize this is WIP, please feel free to re-request a review anytime)

**Comment by derekpierre** [comment]
@cygnusv, so `Ciphertext` comprises of:

```rust
    #[serde_as(as = "serialization::SerdeAs")]
    pub commitment: E::G1Affine,
    // W
    #[serde_as(as = "serialization::SerdeAs")]
    pub auth_tag: E::G2Affine,
    // V
    #[serde(with = "serde_bytes")]
    pub ciphertext: Vec<u8>,
``` 
    
So from a `dem_ciphertext` and `kem_ciphertext` perspective, what is the `kem_ciphertext` here? i.e. what's the ciphertext data I would put in the `ThresholdDecryptionRequest` to send to Ursulas?

**Comment by cygnusv** [comment]
> @cygnusv, so `Ciphertext` comprises of:
> 
> ```rust
>     #[serde_as(as = "serialization::SerdeAs")]
>     pub commitment: E::G1Affine,
>     // W
>     #[serde_as(as = "serialization::SerdeAs")]
>     pub auth_tag: E::G2Affine,
>     // V
>     #[serde(with = "serde_bytes")]
>     pub ciphertext: Vec<u8>,
> ```
> 
> So from a `dem_ciphertext` and `kem_ciphertext` perspective, what is the `kem_ciphertext` here? i.e. what's the ciphertext data I would put in the `ThresholdDecryptionRequest` to send to Ursulas?

Yeah, good question. For the request you only need the commitment, the auth_tag, and the hash of the symmetric ciphertext.

BTW, I'm not sure the term Kem/Dem is technically correct once we introduce the hash of the Dem, but I don't have a better suggestion for the moment.

**Comment by derekpierre** [comment]
> @cygnusv, 👍 thanks for the clarification. Could we do a quick chat about this whenever you are around?

Chatted with @cygnusv , and there will be a follow-up PR to hide some of the Ferveo-specific math details behind higher-level objects.

**Comment by cygnusv** [comment]
> > @cygnusv, 👍 thanks for the clarification. Could we do a quick chat about this whenever you are around?
> 
> Chatted with @cygnusv , and there will be a follow-up PR to hide some of the Ferveo-specific math details behind higher-level objects.

Added new issue #154 to track this

File: tpke/src/ciphertext.rs [hunk 1]
```diff
@@ -2,9 +2,9 @@ use std::ops::Mul;
 
 use ark_ec::{pairing::Pairing, AffineRepr};
 use ark_ff::{One, UniformRand};
-use ark_serialize::{CanonicalSerialize, Compress};
+use ark_serialize::CanonicalSerialize;
 use chacha20poly1305::{
-    aead::{generic_array::GenericArray, Aead, KeyInit},
+    aead::{generic_array::GenericArray, Aead, KeyInit, Payload},
```
Comment (jMyles) [inline tpke/src/ciphertext.rs:7]: Is `Payload` your preferred name at this point?

Comment (cygnusv) [reply tpke/src/ciphertext.rs:7]: That's from the aead crate
https://docs.rs/aead/latest/aead/struct.Payload.html

**Comment by jMyles** [comment]
> @jMyles and @KPrasch identified an important limitation of current ciphertexts and TDec requests construction. 

Credit to Fiddle Kuba ( @kubic71 ) as well.

**Review by KPrasch — APPROVED** [review]
